# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Preq < Formula
  desc ""
  homepage ""
  version "0.0.2-rc37"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/tfrs1/preq/releases/download/v0.0.2-rc37/preq_0.0.2-rc37_Darwin_arm64.tar.gz"
      sha256 "49c675451c919c081770c7295286fa41a180f76acb04af55497337e2aac2e4d2"

      def install
        bin.install "preq"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/tfrs1/preq/releases/download/v0.0.2-rc37/preq_0.0.2-rc37_Darwin_x86_64.tar.gz"
      sha256 "b5d37e580e4c7a038417ce754527d8b49abac68c720927dbf900a338865e9e7e"

      def install
        bin.install "preq"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/tfrs1/preq/releases/download/v0.0.2-rc37/preq_0.0.2-rc37_Linux_x86_64.tar.gz"
      sha256 "1878d64900015883ed22ce4659bbcb87e8e060aef7a62f602818846a70c623c1"

      def install
        bin.install "preq"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/tfrs1/preq/releases/download/v0.0.2-rc37/preq_0.0.2-rc37_Linux_arm64.tar.gz"
      sha256 "11089d6ecc8458c368a6a22d3ac7f23c0022927a36dfecfa241c06e776973b3a"

      def install
        bin.install "preq"
      end
    end
  end
end
