# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Preq < Formula
  desc ""
  homepage ""
  version "0.0.2-rc14"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/tfrs1/preq/releases/download/v0.0.2-rc14/preq_0.0.2-rc14_Darwin_x86_64.tar.gz"
      sha256 "6bb3968f60210a1c70dd5ad6ea8b1ba629551c314fe8add7b0cd1e0229d53dc1"

      def install
        bin.install "preq"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/tfrs1/preq/releases/download/v0.0.2-rc14/preq_0.0.2-rc14_Darwin_arm64.tar.gz"
      sha256 "308080a8c49165aa44632d0c9a76db60353517d7a3da187b36a6ece6967d53df"

      def install
        bin.install "preq"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/tfrs1/preq/releases/download/v0.0.2-rc14/preq_0.0.2-rc14_Linux_x86_64.tar.gz"
      sha256 "99ec455b03a037899cdaf06700abe43efb7ac96ac4a9d9122ffe7855590efbd7"

      def install
        bin.install "preq"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/tfrs1/preq/releases/download/v0.0.2-rc14/preq_0.0.2-rc14_Linux_arm64.tar.gz"
      sha256 "b4242d418198ab22904d26e4d312258929572232b661bedfb03ab77076f81e3c"

      def install
        bin.install "preq"
      end
    end
  end
end
